<?php
/** @var \Codilar\AdvancedShipping\Block\Address\Edit\Map $block */
?>
<?php if ($block->getConfigModel()->getIsEnabled()): ?>
    <div id="address-edit-map" style="width: 100%; height: 400px;margin-bottom: 20px"></div>
    <script type="text/javascript">
        require(['jquery', 'mapLocation', 'Codilar_AdvancedShipping/js/renderer/form'], function ($, Map, formRenderer) {
            var addressEditForm = $('.form-address-edit');
            var latLng = $('<input type="hidden" name="lat_lng" value="" />');
            addressEditForm.append(latLng);
            var m = new Map(document.getElementById('address-edit-map'), function (address) {
                for(var item in address) {
                    latLng.val(Object.values(address.latlng).join(","));
                    formRenderer.populateField(addressEditForm, item, address[item]);
                }
            });
        });
    </script>
<?php endif; ?>